### ISSUE TITLE
Не работает выключение климата. Так же не обновляется статус включения климата.

### ISSUE THREAD

**Issue by oleg-78** [alryaz/hass-pandora-cas#34]
### Следующие действия были мною выполнены перед созданием обращения

- [X] **Успешный вход в мобильное приложение Pandora Connect / Pandora Online.**  
Successful authentication with Pandora Connect / Pandora Online smartphone app.

- [X] **Успешный вход на сайт https://pro.p-on.ru или https://p-on.ru.**  
Successful authentication with web portal.

- [X] **Отсутствуют явные упоминания о несовместимости устройства в README-файле.**  
Any discrete mentions of incompatibility of device missing from README.

- [X] **Смежные обращения по проблеме _отсутствуют_.**  
There are _no issues_ describing similar problem.

- [X] **Лог-файлы интеграции загружены на Pastebin или скопированы в поле ниже.**  
Integration log files uploaded to Pastebin or pasted into the field below.

### Версия интеграции / Integration version

2024.8.2

### Версия Home Assistant / Home Assistant version

2024.10.1

### Способ установки интеграции / Integration install method

HACS (Home Assistant Community Store)

### Модель устройства / Device model

Pandora VX-4G GPS FD

### Описание проблемы / Problem description

Добрый день.
При выключении климата через HA климат не выключается. Причем включить можно, а вот выключить нельзя, не работает.  При этом статус включен или выключен климат не меняется. С родного приложения Pandora все работает.
Автомобиль - Zeekr X.

### Способ воспроизведения / Steps to reproduce

1. Нажимаешь включение климата - switch.1080754313_climate_air_conditioning (климат запускается)
2. Нажимаешь еще раз на ползунок, чтобы выключить климат - климат не выключается, повторное нажатие не дает результата.

### Ожидаемый результат / Expected outcome

Ожидается, что климат должен выключиться.

### Журнал отладки и сообщения об ошибках / Traceback and logging information

Logger: homeassistant.core
Source: core.py:1546
First occurred: 1:26:29 PM (1505 occurrences)
Last logged: 2:25:59 PM

Error in event filter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1546, in async_fire_internal
    if event_data is None or not event_filter(event_data):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pandora_cas/entity.py", line 409, in <lambda>
    lambda x: int(x.data[ATTR_COMMAND_ID]) == command_id
                  ^^^^^^
AttributeError: 'dict' object has no attribute 'data'

**Comment by alryaz** [comment]
Проверьте, пожалуйста, исправляет ли ошибку v2025.2.0.
