### ISSUE TITLE
Unexpected error fetching pandora_cas data

### ISSUE THREAD

**Issue by spectrox** [alryaz/hass-pandora-cas#36]
### Следующие действия были мною выполнены перед созданием обращения

- [X] **Успешный вход в мобильное приложение Pandora Connect / Pandora Online.**  
Successful authentication with Pandora Connect / Pandora Online smartphone app.

- [X] **Успешный вход на сайт https://pro.p-on.ru или https://p-on.ru.**  
Successful authentication with web portal.

- [X] **Отсутствуют явные упоминания о несовместимости устройства в README-файле.**  
Any discrete mentions of incompatibility of device missing from README.

- [X] **Смежные обращения по проблеме _отсутствуют_.**  
There are _no issues_ describing similar problem.

- [X] **Лог-файлы интеграции загружены на Pastebin или скопированы в поле ниже.**  
Integration log files uploaded to Pastebin or pasted into the field below.

### Версия интеграции / Integration version

2024.8.2

### Версия Home Assistant / Home Assistant version

2024.11.1

### Способ установки интеграции / Integration install method

HACS (Home Assistant Community Store)

### Модель устройства / Device model

Pandora DX4GA_V13

### Описание проблемы / Problem description

При загрузке данных с endpoint'а lenta парсинг ивентов падает на отсутствии bit_state_1 в наборе данных. Судя по всему падает на получении данных трека (поездки). В логах ошибка каждые 6 секунд (интервал обновления).

### Способ воспроизведения / Steps to reproduce

Добавить сигнализацию, проехаться на машине, чтобы в ленте были события поездки.

### Ожидаемый результат / Expected outcome

Отсутствие ошибок в логах

### Журнал отладки и сообщения об ошибках / Traceback and logging information

```
Unexpected error fetching pandora_cas data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pandora_cas/__init__.py", line 764, in _async_update_data
    ) = await self.account.async_request_updates()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandora_cas/account.py", line 739, in async_request_updates
    events.append(self._process_ws_event(device, event_obj))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandora_cas/account.py", line 584, in _process_http_event
    event = TrackingEvent.from_dict(data, device_id=device.device_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandora_cas/data.py", line 593, in from_dict
    return cls(**cls.get_dict_args(data, **kwargs))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandora_cas/data.py", line 558, in get_dict_args
    kwargs["bit_state"] = BitStatus(int(data["bit_state_1"]))
                                        ~~~~^^^^^^^^^^^^^^^
KeyError: 'bit_state_1'
```

### Дополнительные сведения / Additional context

На скриншоте привёл как раз вырезку из выдачи по эндпоинту лента с событием, которое не содержит bit_state_1.
Массив last_items скрыл так как так много данных (200+ элементов - судя по всему лог поездки: flags, fuel, speed, ts, x, y).
<img width="326" alt="Screenshot 2024-11-20 at 16 40 12" src="https://github.com/user-attachments/assets/e9cd671a-0c0d-4eec-bf1d-c3b596e68c3f">

**Comment by alryaz** [comment]
Подтверждено, будет исправлено в 2025.2.1.

**Comment by alryaz** [comment]
https://github.com/alryaz/hass-pandora-cas/releases/tag/v2025.2.1

Попробуйте обновить (является пререлизной).

Тамошняя обработка событий кардинально изменилась.
